# Generated by Django 4.2.1 on 2023-06-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_total_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orderd',
            new_name='ordered',
        ),
    ]
